#version 450 core
// --- Deferred Lighting Pass Vertex Shader ---
// Purpose: Renders the Light Volume (Sphere) geometry.
// The fragments generated by this sphere will be processed by the fragment shader
// to calculate lighting for pixels *inside* the volume.

layout (location = 0) in vec3 aPos;

// Uniforms
layout (location = 0) uniform mat4 model;      // Light Sphere transform (scaled by Radius)
layout (location = 1) uniform mat4 view;
layout (location = 2) uniform mat4 projection;

void main()
{
    gl_Position = projection * view * model * vec4(aPos, 1.0);
}
